services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./demo:/sites/demo
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
