version: '3'
services:
  nifi:
    image: apache/nifi
    container_name: nifi
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - ./drivers:/opt/nifi/nifi-current/drivers/
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
