package model;
// Generated Aug 31, 2019 9:42:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * NguoiDung generated by hbm2java
 */
public class NguoiDung  implements java.io.Serializable {


     private int id;
     private String email;
     private Serializable hoTen;
     private String matKhau;
     private boolean chucVu;
     private boolean khoa;
     private boolean trangThai;
     private Set<PhieuMua> phieuMuas = new HashSet<PhieuMua>(0);

    public NguoiDung() {
    }

	
    public NguoiDung(int id, String email, Serializable hoTen, String matKhau, boolean chucVu, boolean khoa, boolean trangThai) {
        this.id = id;
        this.email = email;
        this.hoTen = hoTen;
        this.matKhau = matKhau;
        this.chucVu = chucVu;
        this.khoa = khoa;
        this.trangThai = trangThai;
    }
    public NguoiDung(int id, String email, Serializable hoTen, String matKhau, boolean chucVu, boolean khoa, boolean trangThai, Set<PhieuMua> phieuMuas) {
       this.id = id;
       this.email = email;
       this.hoTen = hoTen;
       this.matKhau = matKhau;
       this.chucVu = chucVu;
       this.khoa = khoa;
       this.trangThai = trangThai;
       this.phieuMuas = phieuMuas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Serializable getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(Serializable hoTen) {
        this.hoTen = hoTen;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public boolean isChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(boolean chucVu) {
        this.chucVu = chucVu;
    }
    public boolean isKhoa() {
        return this.khoa;
    }
    
    public void setKhoa(boolean khoa) {
        this.khoa = khoa;
    }
    public boolean isTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(boolean trangThai) {
        this.trangThai = trangThai;
    }
    public Set<PhieuMua> getPhieuMuas() {
        return this.phieuMuas;
    }
    
    public void setPhieuMuas(Set<PhieuMua> phieuMuas) {
        this.phieuMuas = phieuMuas;
    }




}


