package model;
// Generated Aug 31, 2019 9:42:18 AM by Hibernate Tools 4.3.1



/**
 * PhieuMuaChiTietId generated by hbm2java
 */
public class PhieuMuaChiTietId  implements java.io.Serializable {


     private int id;
     private int maSanPham;

    public PhieuMuaChiTietId() {
    }

    public PhieuMuaChiTietId(int id, int maSanPham) {
       this.id = id;
       this.maSanPham = maSanPham;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(int maSanPham) {
        this.maSanPham = maSanPham;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PhieuMuaChiTietId) ) return false;
		 PhieuMuaChiTietId castOther = ( PhieuMuaChiTietId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getMaSanPham()==castOther.getMaSanPham());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getMaSanPham();
         return result;
   }   


}


