package model;
// Generated Aug 31, 2019 9:42:18 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SanPham generated by hbm2java
 */
public class SanPham  implements java.io.Serializable {


     private int maSanPham;
     private Serializable tenSanPham;
     private BigDecimal gia;
     private Serializable hinh;
     private int soLuong;
     private Set<PhieuMuaChiTiet> phieuMuaChiTiets = new HashSet<PhieuMuaChiTiet>(0);

    public SanPham() {
    }

	
    public SanPham(int maSanPham, Serializable tenSanPham, BigDecimal gia, Serializable hinh, int soLuong) {
        this.maSanPham = maSanPham;
        this.tenSanPham = tenSanPham;
        this.gia = gia;
        this.hinh = hinh;
        this.soLuong = soLuong;
    }
    public SanPham(int maSanPham, Serializable tenSanPham, BigDecimal gia, Serializable hinh, int soLuong, Set<PhieuMuaChiTiet> phieuMuaChiTiets) {
       this.maSanPham = maSanPham;
       this.tenSanPham = tenSanPham;
       this.gia = gia;
       this.hinh = hinh;
       this.soLuong = soLuong;
       this.phieuMuaChiTiets = phieuMuaChiTiets;
    }
   
    public int getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(int maSanPham) {
        this.maSanPham = maSanPham;
    }
    public Serializable getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(Serializable tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public BigDecimal getGia() {
        return this.gia;
    }
    
    public void setGia(BigDecimal gia) {
        this.gia = gia;
    }
    public Serializable getHinh() {
        return this.hinh;
    }
    
    public void setHinh(Serializable hinh) {
        this.hinh = hinh;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public Set<PhieuMuaChiTiet> getPhieuMuaChiTiets() {
        return this.phieuMuaChiTiets;
    }
    
    public void setPhieuMuaChiTiets(Set<PhieuMuaChiTiet> phieuMuaChiTiets) {
        this.phieuMuaChiTiets = phieuMuaChiTiets;
    }




}


