version: "3.3"

services:
  database:
    image: mariadb
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dht24111997
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./volume:/var/lib/mysql
    ports:
      - 3306:3306

