-- remove
ALTER TABLE CUSTOMER_SALES
DROP ROW ACCESS POLICY region_filter;

ALTER TABLE CUSTOMER_SALES
ALTER COLUMN EMAIL
unset MASKING POLICY;

CREATE OR REPLACE TABLE CUSTOMER_SALES (
    CUSTOMER_ID INT,
    REGION STRING,
    EMAIL STRING,
    SALES_AMOUNT NUMBER
);

INSERT INTO CUSTOMER_SALES VALUES
(1, 'APAC', 'alice@example.com', 5000),
(2, 'EU',   'bob@example.com',   7000),
(3, 'US',   'carol@example.com', 9000);

-- Row Access Policy
CREATE OR REPLACE ROW ACCESS POLICY region_filter
AS (region STRING) RETURNS BOOLEAN ->
    -- CURRENT_ROLE() IN ('APAC_ROLE') AND region = 'APAC';
    region = 'APAC';

ALTER TABLE CUSTOMER_SALES
ADD ROW ACCESS POLICY region_filter ON (REGION);

-- Dynamic Data Masking Policy
CREATE OR REPLACE MASKING POLICY email_mask
AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('FULL_ACCESS_ROLE') THEN val
        ELSE '*******'
    END
EXEMPT_OTHER_POLICIES = FALSE;

ALTER TABLE CUSTOMER_SALES
-- ALTER COLUMN EMAIL
ALTER COLUMN REGION
SET MASKING POLICY email_mask;

-- Query Execution
SELECT * FROM CUSTOMER_SALES;




