-- SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM sample (10 rows);
-- SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM;

-- SELECT 
--   SYSTEM$ESTIMATE_STATS('SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM');


-- SELECT *
--   FROM SNOWFLAKE_SAMPLE_DATA.INFORMATION_SCHEMA.TABLE_STORAGE_METRICS
--   where table_schema = 'TPCH_SF1000'
--   GROUP BY TABLE_SCHEMA;

-- select avg(l_quantity) from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM

-- USE DATABASE SNOWFLAKE;
-- USE SCHEMA LOCAL;
-- SELECT *
--   FROM TABLE(SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS(
--     REF_ENTITY_NAME => 'SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM',
--     REF_ENTITY_DOMAIN => 'table'));

-- SELECT *
--   FROM TABLE(SYSTEM$DATA_METRIC_SCAN(
--     REF_ENTITY_NAME  => 'SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM',
--     METRIC_NAME  => 'snowflake.core.null_count',
--     ARGUMENT_NAME => 'l_quantity'
--   ));

-- SELECT *
--   FROM TABLE(SYSTEM$DATA_METRIC_SCAN(
--     REF_ENTITY_NAME  => 'governance.sch.employeesTable',
--     METRIC_NAME  => 'snowflake.core.null_count',
--     ARGUMENT_NAME => 'SSN'
--   ));

-- select * from SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_RESULTS_RAW
-- select * from SNOWFLAKE.LOCAL.DATA_QUALITY_MONITORING_ANOMALY_DETECTION_STATUS

-- DATA_QUALITY_MONITORING_ANOMALY_DETECTION











OBJECT_KEYS