package hibernate.entity;
// Generated Aug 9, 2019 3:31:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PhieuMua generated by hbm2java
 */
public class PhieuMua  implements java.io.Serializable {


     private int id;
     private NguoiDung nguoiDung;
     private String maPhieu;
     private Boolean trangThai;
     private Set<PhieuMuaChiTiet> phieuMuaChiTiets = new HashSet<PhieuMuaChiTiet>(0);

    public PhieuMua() {
    }

	
    public PhieuMua(int id, NguoiDung nguoiDung, String maPhieu) {
        this.id = id;
        this.nguoiDung = nguoiDung;
        this.maPhieu = maPhieu;
    }
    public PhieuMua(int id, NguoiDung nguoiDung, String maPhieu, Boolean trangThai, Set<PhieuMuaChiTiet> phieuMuaChiTiets) {
       this.id = id;
       this.nguoiDung = nguoiDung;
       this.maPhieu = maPhieu;
       this.trangThai = trangThai;
       this.phieuMuaChiTiets = phieuMuaChiTiets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public NguoiDung getNguoiDung() {
        return this.nguoiDung;
    }
    
    public void setNguoiDung(NguoiDung nguoiDung) {
        this.nguoiDung = nguoiDung;
    }
    public String getMaPhieu() {
        return this.maPhieu;
    }
    
    public void setMaPhieu(String maPhieu) {
        this.maPhieu = maPhieu;
    }
    public Boolean getTrangThai() {
        return this.trangThai;
    }
    
    public void setTrangThai(Boolean trangThai) {
        this.trangThai = trangThai;
    }
    public Set<PhieuMuaChiTiet> getPhieuMuaChiTiets() {
        return this.phieuMuaChiTiets;
    }
    
    public void setPhieuMuaChiTiets(Set<PhieuMuaChiTiet> phieuMuaChiTiets) {
        this.phieuMuaChiTiets = phieuMuaChiTiets;
    }




}


