package hibernate.entity;
// Generated Aug 9, 2019 3:31:37 PM by Hibernate Tools 4.3.1



/**
 * PhieuMuaChiTiet generated by hbm2java
 */
public class PhieuMuaChiTiet  implements java.io.Serializable {


     private PhieuMuaChiTietId id;
     private PhieuMua phieuMua;
     private SanPham sanPham;
     private int soLuongDaMua;

    public PhieuMuaChiTiet() {
    }

    public PhieuMuaChiTiet(PhieuMuaChiTietId id, PhieuMua phieuMua, SanPham sanPham, int soLuongDaMua) {
       this.id = id;
       this.phieuMua = phieuMua;
       this.sanPham = sanPham;
       this.soLuongDaMua = soLuongDaMua;
    }
   
    public PhieuMuaChiTietId getId() {
        return this.id;
    }
    
    public void setId(PhieuMuaChiTietId id) {
        this.id = id;
    }
    public PhieuMua getPhieuMua() {
        return this.phieuMua;
    }
    
    public void setPhieuMua(PhieuMua phieuMua) {
        this.phieuMua = phieuMua;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public int getSoLuongDaMua() {
        return this.soLuongDaMua;
    }
    
    public void setSoLuongDaMua(int soLuongDaMua) {
        this.soLuongDaMua = soLuongDaMua;
    }




}


