package hibernate.entity;
// Generated Aug 9, 2019 3:31:37 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * SanPham generated by hbm2java
 */
public class SanPham  implements java.io.Serializable {


     private int maSanPham;
     private String tenSanPham;
     private BigDecimal gia;
     private String hinh;
     private int soLuong;
     private Set<PhieuMuaChiTiet> phieuMuaChiTiets = new HashSet<PhieuMuaChiTiet>(0);

    public SanPham() {
    }

	
    public SanPham(int maSanPham, String tenSanPham, BigDecimal gia, String hinh, int soLuong) {
        this.maSanPham = maSanPham;
        this.tenSanPham = tenSanPham;
        this.gia = gia;
        this.hinh = hinh;
        this.soLuong = soLuong;
    }
    public SanPham(int maSanPham, String tenSanPham, BigDecimal gia, String hinh, int soLuong, Set<PhieuMuaChiTiet> phieuMuaChiTiets) {
       this.maSanPham = maSanPham;
       this.tenSanPham = tenSanPham;
       this.gia = gia;
       this.hinh = hinh;
       this.soLuong = soLuong;
       this.phieuMuaChiTiets = phieuMuaChiTiets;
    }
   
    public int getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(int maSanPham) {
        this.maSanPham = maSanPham;
    }
    public String getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public BigDecimal getGia() {
        return this.gia;
    }
    
    public void setGia(BigDecimal gia) {
        this.gia = gia;
    }
    public String getHinh() {
        return this.hinh;
    }
    
    public void setHinh(String hinh) {
        this.hinh = hinh;
    }
    public int getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }
    public Set<PhieuMuaChiTiet> getPhieuMuaChiTiets() {
        return this.phieuMuaChiTiets;
    }
    
    public void setPhieuMuaChiTiets(Set<PhieuMuaChiTiet> phieuMuaChiTiets) {
        this.phieuMuaChiTiets = phieuMuaChiTiets;
    }




}


