package model;
// Generated Sep 12, 2019 6:36:26 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SanPham generated by hbm2java
 */
public class SanPham  implements java.io.Serializable {


     private int id;
     private String tenSanPham;
     private BigDecimal giaCu;
     private int giamGia;

    public SanPham() {
    }

    public SanPham(int id, String tenSanPham, BigDecimal giaCu, int giamGia) {
       this.id = id;
       this.tenSanPham = tenSanPham;
       this.giaCu = giaCu;
       this.giamGia = giamGia;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public BigDecimal getGiaCu() {
        return this.giaCu;
    }
    
    public void setGiaCu(BigDecimal giaCu) {
        this.giaCu = giaCu;
    }
    public int getGiamGia() {
        return this.giamGia;
    }
    
    public void setGiamGia(int giamGia) {
        this.giamGia = giamGia;
    }




}


