version: "3.3"

services:
  database:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

