package hibernate.entity;
// Generated Aug 2, 2019 3:08:59 PM by Hibernate Tools 4.3.1

import java.io.Serializable;

/**
 * NhanVien generated by hbm2java
 */
public class NhanVien implements java.io.Serializable {

    private int maNhanVien;
    private PhongBan phongBan;
    private String tenNhanVien;
    private String email;

    public NhanVien() {
    }

    public NhanVien(int maNhanVien, PhongBan phongBan, String tenNhanVien, String email) {
        this.maNhanVien = maNhanVien;
        this.phongBan = phongBan;
        this.tenNhanVien = tenNhanVien;
        this.email = email;
    }

    public int getMaNhanVien() {
        return this.maNhanVien;
    }

    public void setMaNhanVien(int maNhanVien) {
        this.maNhanVien = maNhanVien;
    }

    public PhongBan getPhongBan() {
        return this.phongBan;
    }

    public void setPhongBan(PhongBan phongBan) {
        this.phongBan = phongBan;
    }

    public String getTenNhanVien() {
        return this.tenNhanVien;
    }

    public void setTenNhanVien(String tenNhanVien) {
        this.tenNhanVien = tenNhanVien;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
