package hibernate.entity;
// Generated Aug 2, 2019 3:08:59 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PhongBan generated by hbm2java
 */
public class PhongBan  implements java.io.Serializable {


     private int maPhong;
     private String tenPhong;
     private Set<NhanVien> nhanViens = new HashSet<NhanVien>(0);

    public PhongBan() {
    }

	
    public PhongBan(int maPhong) {
        this.maPhong = maPhong;
    }
    public PhongBan(int maPhong, String tenPhong, Set<NhanVien> nhanViens) {
       this.maPhong = maPhong;
       this.tenPhong = tenPhong;
       this.nhanViens = nhanViens;
    }
   
    public int getMaPhong() {
        return this.maPhong;
    }
    
    public void setMaPhong(int maPhong) {
        this.maPhong = maPhong;
    }
    public String getTenPhong() {
        return this.tenPhong;
    }
    
    public void setTenPhong(String tenPhong) {
        this.tenPhong = tenPhong;
    }
    public Set<NhanVien> getNhanViens() {
        return this.nhanViens;
    }
    
    public void setNhanViens(Set<NhanVien> nhanViens) {
        this.nhanViens = nhanViens;
    }




}


