version: "3.5"

services:
  CentosNameNode:
    image: centos:7
    container_name: centosNameNode
    ports: 
      - 8080:8080
    networks:
      network_Hadoop:
        ipv4_address: 172.29.0.2
    extra_hosts:
      - "master.hadoop.com:172.29.0.2"
      - "worker1.hadoop.com:172.29.0.3"
      - "worker2.hadoop.com:172.29.0.4"
    privileged: true
    command: /sbin/init
    # stdin_open: true
    # stdin (standard input: cho phép đưa input vào bằng bàn phím)
    # Giữ STDIN mở ngay cả khi không được attach
    # tty: true
    # teletype writer (giống như cái máy đánh chữ hoặc là cái máy tính cũ, chỉ có thể chạy các process bằng terminal)
    # chỉ định 1 tty giả, ý nghĩ nó cũng giống như cái stdin_open

    # docker container exit if there is no running application, process in the container, thế nên là phải add thêm cái stdin_open or tty vào cho nó không exit nữa

  CentosDataNode1:
    image: centos:7
    container_name: centosDataNode1
    networks:
      network_Hadoop:
        ipv4_address: 172.29.0.3
    extra_hosts:
      - "master.hadoop.com:172.29.0.2"
      - "worker1.hadoop.com:172.29.0.3"
      - "worker2.hadoop.com:172.29.0.4"
    ports: 
      - 50071:50070
    stdin_open: true
    privileged: true
    command: /sbin/init

  CentosDataNode2:
    image: centos:7
    container_name: centosDataNode2
    networks:
      network_Hadoop:
        ipv4_address: 172.29.0.4
    extra_hosts:
      - "master.hadoop.com:172.29.0.2"
      - "worker1.hadoop.com:172.29.0.3"
      - "worker2.hadoop.com:172.29.0.4"
    ports: 
      - 50072:50070
    stdin_open: true
    privileged: true
    command: /sbin/init

networks:
  network_Hadoop:
    name: network_Hadoop
    driver: bridge
    ipam: 
      config: 
        - subnet: 172.29.0.0/16
