version: "3.3"

services:
  database:
    image: postgres@sha256:97e5e91582e89514277912d4b7c95bceabdede3482e32395bcb40099abd9c506
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5433:5432

