version: "3.5"

services:
  mongoTestReplicaSet0:
    # tạo container từ image mongo 3.2
    image: mongo:3.2.0
    # đặt hostname
    container_name: mongo0
    # tạo volume mount với folder /data/db của container
    volumes:
      - volume_test_replicaset_0:/data/db
    # liên kết port 27017 của localhost với port 27017 của container
    ports:
      - 27017:27017
    # đặt tên replica set và chỉ định --bind_ip
    command: --replSet rs0 --bind_ip localhost,mongo0 --logpath /var/log/mongodb/log.log
    networks:
      network_test_replica_set:
    # extra_hosts:
    #   - "mongo0:192.168.0.119"
    #   - "mongo1:192.168.0.119"
    #   - "mongo2:192.168.0.119"

  mongoTestReplicaSet1:
    image: mongo:3.2.0
    container_name: mongo1
    volumes:
      - volume_test_replicaset_1:/data/db
    ports:
      - 27018:27017
    command: --replSet rs0 --bind_ip localhost,mongo1 --logpath /var/log/mongodb/log.log
    networks:
      network_test_replica_set:

  mongoTestReplicaSet2:
    image: mongo:3.2.0
    container_name: mongo2
    volumes:
      - volume_test_replicaset_2:/data/db
    ports:
      - 27019:27017
    command: --replSet rs0 --bind_ip localhost,mongo2 --logpath /var/log/mongodb/log.log
    networks:
      network_test_replica_set:

volumes:
  volume_test_replicaset_0:
    name: volume_test_replicaset_0
  volume_test_replicaset_1:
    name: volume_test_replicaset_1
  volume_test_replicaset_2:
    name: volume_test_replicaset_2

networks:
  network_test_replica_set:
    name: network_test_replica_set
    driver: bridge
