package fpoly.entity;
// Generated Jul 22, 2019 4:35:42 PM by Hibernate Tools 4.3.1



/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private String maKhachHang;
     private String matKhau;
     private String hoTen;
     private String email;
     private String dienThoai;

    public Customers() {
    }

	
    public Customers(String maKhachHang) {
        this.maKhachHang = maKhachHang;
    }
    public Customers(String maKhachHang, String matKhau, String hoTen, String email, String dienThoai) {
       this.maKhachHang = maKhachHang;
       this.matKhau = matKhau;
       this.hoTen = hoTen;
       this.email = email;
       this.dienThoai = dienThoai;
    }
   
    public String getMaKhachHang() {
        return this.maKhachHang;
    }
    
    public void setMaKhachHang(String maKhachHang) {
        this.maKhachHang = maKhachHang;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }




}


