package fpoly.entity;
// Generated Jul 31, 2019 4:34:55 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * KhachHang generated by hbm2java
 */
public class KhachHang  implements java.io.Serializable {


     private int maKhachHang;
     private String ten;
     private String email;
     private String matKhau;
     private String sdt;

    public KhachHang() {
    }

    public KhachHang(int maKhachHang, String ten, String email, String matKhau, String sdt) {
       this.maKhachHang = maKhachHang;
       this.ten = ten;
       this.email = email;
       this.matKhau = matKhau;
       this.sdt = sdt;
    }
   
    public int getMaKhachHang() {
        return this.maKhachHang;
    }
    
    public void setMaKhachHang(int maKhachHang) {
        this.maKhachHang = maKhachHang;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }




}


